name: Moodle Plugin CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        moodle-branch: [MOODLE_405_STABLE]
        php: ['8.2']
        database: [pgsql]

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: moodle
          POSTGRES_USER: moodle
          POSTGRES_PASSWORD: moodle
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U moodle"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pgsql, intl, mbstring, xml, curl, zip
          tools: composer

      - name: Install moodle-plugin-ci
        run: |
          composer global require moodlehq/moodle-plugin-ci
          echo "$HOME/.composer/vendor/bin" >> $GITHUB_PATH

      - name: Install Moodle
        run: |
          moodle-plugin-ci install \
          --db-type=pgsql \
          --db-host=127.0.0.1 \
          --db-user=moodle \
          --db-pass=moodle \
          --db-name=moodle \
          --moodle=${{ matrix.moodle-branch }}

      - name: PHP lint
        run: moodle-plugin-ci phplint

      - name: Moodle code checker
        run: moodle-plugin-ci phpcs

      - name: PHPUnit tests
        run: moodle-plugin-ci phpunit

